/products:
  get:
    tags:
      - Product
    summary: 상품 목록 조회
    description: |
      상품 목록을 조회합니다.

      **기능 요구사항**: FR-P-001
      **관련 문서**: docs/requirements/product.md

      **비즈니스 규칙**:
      - 삭제된 상품 제외
      - 비활성화된 상품 제외
      - 정렬 옵션: newest(최신순), popular(인기순), price_low(낮은가격순), price_high(높은가격순)
    operationId: getProducts
    parameters:
      - name: categoryId
        in: query
        description: 카테고리 ID
        required: false
        schema:
          type: integer
          example: 1
      - name: page
        in: query
        description: 페이지 번호
        required: false
        schema:
          type: integer
          minimum: 1
          default: 1
      - name: size
        in: query
        description: 페이지 크기
        required: false
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 20
      - name: sortBy
        in: query
        description: 정렬 기준
        required: false
        schema:
          type: string
          enum: [newest, popular, price_low, price_high]
          default: newest
    responses:
      '200':
        description: 조회 성공
        content:
          application/json:
            schema:
              $ref: '../schemas/product.yaml#/components/schemas/ProductListResponse'
      '400':
        description: 잘못된 요청
        content:
          application/json:
            schema:
              $ref: '../schemas/common.yaml#/components/schemas/Error'
            example:
              code: "CATEGORY_NOT_FOUND"
              message: "카테고리를 찾을 수 없습니다"
      '500':
        description: 서버 오류

/products/{productId}:
  get:
    tags:
      - Product
    summary: 상품 상세 조회
    description: |
      특정 상품의 상세 정보를 조회합니다.

      **기능 요구사항**: FR-P-002
      **관련 문서**: docs/requirements/product.md

      **비즈니스 규칙**:
      - 조회 시 조회수 1 증가
      - 삭제된 상품은 조회 불가
      - 판매 불가능한 옵션도 표시 (구매는 불가)
    operationId: getProduct
    parameters:
      - name: productId
        in: path
        description: 상품 ID
        required: true
        schema:
          type: integer
          example: 10
    responses:
      '200':
        description: 조회 성공
        content:
          application/json:
            schema:
              $ref: '../schemas/product.yaml#/components/schemas/ProductDetailResponse'
      '404':
        description: 상품을 찾을 수 없음
        content:
          application/json:
            schema:
              $ref: '../schemas/common.yaml#/components/schemas/Error'
            examples:
              productNotFound:
                summary: 상품 없음
                value:
                  code: "PRODUCT_NOT_FOUND"
                  message: "상품을 찾을 수 없습니다"
              productDeleted:
                summary: 삭제된 상품
                value:
                  code: "PRODUCT_DELETED"
                  message: "삭제된 상품입니다"
      '500':
        description: 서버 오류

/products/{productId}/options:
  get:
    tags:
      - Product
    summary: 상품 옵션 목록 조회
    description: |
      특정 상품의 옵션 목록을 조회합니다.

      **기능 요구사항**: FR-P-003
      **관련 문서**: docs/requirements/product.md

      **비즈니스 규칙**:
      - 모든 옵션 조회 (판매 가능/불가능 모두)
    operationId: getProductOptions
    parameters:
      - name: productId
        in: path
        description: 상품 ID
        required: true
        schema:
          type: integer
          example: 10
    responses:
      '200':
        description: 조회 성공
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
                - productName
                - options
              properties:
                productId:
                  type: integer
                  example: 10
                productName:
                  type: string
                  example: "기본 라운드 티셔츠"
                options:
                  type: array
                  items:
                    $ref: '../schemas/product.yaml#/components/schemas/ProductOption'
      '404':
        description: 상품을 찾을 수 없음
        content:
          application/json:
            schema:
              $ref: '../schemas/common.yaml#/components/schemas/Error'
            example:
              code: "PRODUCT_NOT_FOUND"
              message: "상품을 찾을 수 없습니다"
      '500':
        description: 서버 오류

/products/popular:
  get:
    tags:
      - Product
    summary: 인기 상품 조회 (Top 5)
    description: |
      최근 3일간 판매량 기준 상위 5개 상품을 조회합니다.

      **기능 요구사항**: FR-P-008
      **관련 문서**: docs/requirements/product.md

      **비즈니스 규칙**:
      - 최근 3일간 완료된 주문의 order_items 집계
      - 판매 수량 기준 내림차순 정렬
      - 상위 5개 반환
    operationId: getPopularProducts
    responses:
      '200':
        description: 조회 성공
        content:
          application/json:
            schema:
              $ref: '../schemas/product.yaml#/components/schemas/PopularProductsResponse'
      '500':
        description: 서버 오류
